using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.SampleA.Services
{
    public partial class DbCountry
    {
        public DbCountry()
        {
        }

        public virtual long MyTableId { get; set; }
        public virtual Guid rowguid { get; set; }
        public virtual DateTime? CreationDate { get; set; }
        public virtual DateTime? LastModificationDate { get; set; }
        public virtual string Name { get; set; }
        public virtual string DisplayName { get; set; }
        public virtual string Description { get; set; }
    }
}
